In [1]:
import numpy as np

## que 1. write  code to create a 4x3 matrix with values ranging fro 2 to 13

In [2]:
arr1 = np.arange(2,14).reshape(4,3)
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

## que 2.write a code to replace the odd numbers by -1 in the array created by using random.randint(1,50,20)

In [3]:
arr2 = np.random.randint(1,50,20)
arr2

array([35, 20,  8, 13, 21,  1, 48,  1, 23, 34, 19,  3,  1, 44, 24,  3, 30,
       36, 31, 26], dtype=int32)

In [4]:
arr2 =np.where(arr2 % 2 != 0, -1, arr2)
arr2

array([-1, 20,  8, -1, -1, -1, 48, -1, -1, 34, -1, -1, -1, 44, 24, -1, 30,
       36, -1, 26], dtype=int32)

## que 3. perform the following operations on an array of mobile phones prices 6999, 7500, 11999,27899, 14999,9999.


### a . create a ID-array of mobile phones prices

In [5]:
id_array = np. array([6999, 7500, 11999, 27899, 14999,9999])
id_array

array([ 6999,  7500, 11999, 27899, 14999,  9999])

### b. convert this array into float type

In [6]:
arr_float = id_array.astype(float)
arr_float

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

### c. append a new mobile having price of 13999 rs. to this array

In [7]:
arr =  np.append(id_array, 13999)
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

### d. Reverse this array of mobile phones prices

In [8]:
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

In [9]:
reversed_arr= arr[::-1]
reversed_arr

array([13999,  9999, 14999, 27899, 11999,  7500,  6999])

### e. Apply GST of 18% on mobile phones prices and update this array

In [10]:
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

In [11]:
gst_rate =0.18
update_arr= arr*(1+gst_rate)
update_arr

array([ 8258.82,  8850.  , 14158.82, 32920.82, 17698.82, 11798.82,
       16518.82])

### f. Sort the array in descending order of price

In [12]:
arr

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

In [16]:
sort_arr=np.sort(arr)[::-1]
sort_arr

array([27899, 14999, 13999, 11999,  9999,  7500,  6999])

### g. What is the average mobile phone price

In [17]:
arr

array([ 6999,  7500,  9999, 11999, 13999, 14999, 27899])

In [18]:
average_phone_price = arr.mean()
average_phone_price

np.float64(13342.0)

### h.What is the difference betweeen maximum and minimum price

In [19]:
arr

array([ 6999,  7500,  9999, 11999, 13999, 14999, 27899])

In [20]:
max_arr = arr.max()
max_arr

np.int64(27899)

In [21]:
min_arr =arr.min()
min_arr

np.int64(6999)

## Que4.Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [22]:
arr = np.array([1,2,0,0,4,0])
arr

array([1, 2, 0, 0, 4, 0])

In [23]:
indices = np.nonzero(arr)
indices

(array([0, 1, 4]),)