In [1]:
import numpy as np

### que 1. Create a Numpy array containing integers from 0 to 9

In [2]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## que2. Create a NumPy array from a given Python list [10,20,30,40,50]

In [3]:
list = [10,20,30,40,50]
arr =np.array(list)
arr

array([10, 20, 30, 40, 50])

## que 3. Create a 2D array (3x3) with values ranging from 0 to 8

In [4]:
arr= np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Given 2D array, find its shape and size. Create 5x4  array with random integers between 1 and 100 , and print the shape and size

In [5]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr.shape

(3, 3)

In [7]:
arr.size

9

In [8]:
arr1 = np.random.randint(1,100,20).reshape(5,4)
arr1

array([[67, 37, 78, 80],
       [40, 94, 92, 96],
       [53,  9, 24, 84],
       [96, 44,  5, 95],
       [17, 64, 53, 34]], dtype=int32)

In [9]:
arr1.shape

(5, 4)

In [10]:
arr1.size

20

## 5. Create 3x3 array of integers and access

In [11]:
arr = np. random.randint(1,50,9).reshape(3,3)
arr

array([[14, 14, 34],
       [ 8, 35,  6],
       [40, 34, 44]], dtype=int32)

### a. The second element of the first row

In [12]:
arr[1,1]

np.int32(35)

### b. The third column of the 2nd row

In [13]:
arr[1,2]

np.int32(6)

### c. A subarray with the first two rows and last two column

In [14]:
arr[0:2,1:3]

array([[14, 34],
       [35,  6]], dtype=int32)

## que 6. Create 1D array of 12 elements. Reshape it into a 3x4 2D array

In [15]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
arr = arr.reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 7. Reshape 3x3 matrix into 1D array

In [17]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
re_arr =arr.reshape(-1)
re_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## 8. Create two array of shape(2,3): arr1 and arr2. Perform element-wise addition, substraction, multiplication, and division on them

In [19]:
arr1= np.random.randint(1,50,6).reshape(2,3)
arr1

array([[12, 15, 12],
       [22, 14, 43]], dtype=int32)

In [20]:
arr2= np.random.randint(1,50,6).reshape(2,3)
arr2

array([[24,  2, 18],
       [13, 17, 36]], dtype=int32)

In [21]:
addition= arr1+arr2
addition

array([[36, 17, 30],
       [35, 31, 79]], dtype=int32)

In [22]:
substraction= arr1-arr2
substraction

array([[-12,  13,  -6],
       [  9,  -3,   7]], dtype=int32)

In [23]:
multiplication= arr1* arr2
multiplication

array([[ 288,   30,  216],
       [ 286,  238, 1548]], dtype=int32)

In [24]:
division= arr1/arr2
division

array([[0.5       , 7.5       , 0.66666667],
       [1.69230769, 0.82352941, 1.19444444]])

## que 9. Use NumPys built in functions to compute the sum, mean, and standard deviation of a given array.

In [25]:
arr= np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Compute sum

In [26]:
arr_sum= np.sum(arr)
arr_sum

np.int64(45)

### compute mean

In [27]:
arr_mean=np.mean(arr)
arr_mean

np.float64(4.5)

### compute standard deviation

In [28]:
arr_devi=np.std(arr)
arr_devi

np.float64(2.8722813232690143)

## que 10. create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @operator.

In [29]:
A = np.random.randint(1,10,4).reshape(2,2)
B= np.random.randint(1,10,4).reshape(2,2)


In [30]:
A

array([[1, 5],
       [3, 3]], dtype=int32)

In [31]:
B

array([[9, 9],
       [7, 9]], dtype=int32)

#### using np.dot()

In [32]:
C_dot = np.dot(A, B)
C_dot

array([[44, 54],
       [48, 54]], dtype=int32)

#### @ operator

In [33]:
C_at = A @ B
C_at

array([[44, 54],
       [48, 54]], dtype=int32)

## Que 11. Find the transpose of matrix A and matrix B.

In [34]:
A

array([[1, 5],
       [3, 3]], dtype=int32)

In [36]:
transpose_a=np.transpose(A)
transpose_a

array([[1, 3],
       [5, 3]], dtype=int32)

In [37]:
B

array([[9, 9],
       [7, 9]], dtype=int32)

In [38]:
transpose_b=np.transpose(B)
transpose_b

array([[9, 7],
       [9, 9]], dtype=int32)

## Que12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [39]:
A= np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
B= np.array([1,2,3])
B

array([1, 2, 3])

In [42]:
C=A+B
C

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

#### Broadcasting allows NumPy to apply the 1D array [1, 2, 3] to each row of the 3×3 matrix automatically — no loops, no manual replication.

## Que13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array

In [43]:
arr_random= np.random.randint(1,50,16).reshape(4,4)
arr_random

array([[48, 16, 21, 22],
       [ 2, 14, 17, 34],
       [31, 35,  4, 12],
       [17, 42, 35,  6]], dtype=int32)

In [44]:
arr_random.max()

np.int32(48)

In [45]:
arr_random.min()

np.int32(2)

In [46]:
arr_random.mean()

np.float64(22.25)

## Que14. Find the row-wise and column-wise sums.


In [47]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
row_sum=arr.sum(axis=0)
row_sum

array([ 9, 12, 15])

In [50]:
col_sum=arr.sum(axis=1)
col_sum

array([ 3, 12, 21])

## Que15.Generate an array of 10 random integers between 1 and 50.


In [52]:
arr= np.random.randint(1,50,10)
arr

array([39, 36, 46,  8, 10, 39, 38, 11, 14, 46], dtype=int32)

## Que16.Generate a 5x5 matrix of random floats between 0 and 1.

In [58]:
matrix = np.random.rand(5, 5)
matrix

array([[0.33868209, 0.34301747, 0.07644216, 0.99892944, 0.39136276],
       [0.06683145, 0.99441214, 0.84002736, 0.13502277, 0.23832619],
       [0.52582146, 0.94867933, 0.55116501, 0.71254935, 0.38337627],
       [0.84931387, 0.22991662, 0.26693569, 0.77752447, 0.10537035],
       [0.06644694, 0.18588131, 0.59510916, 0.99616595, 0.78625726]])