In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
arr2 = np.array([1,2,'fbs',3,4])

In [5]:
arr1.dtype

dtype('int64')

In [6]:
arr2.dtype

dtype('<U21')

In [7]:
arr2

array(['1', '2', 'fbs', '3', '4'], dtype='<U21')

## Vectorization

In [8]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])

In [10]:
arr3 = arr1+arr2
arr3

array([ 7,  9, 11, 13])

In [11]:
arr1 =arr2*10
arr1

array([60, 70, 80, 90])

In [12]:
arr1 = arr1//2
arr1

array([30, 35, 40, 45])

In [13]:
arr2 =arr2//2
arr2

array([3, 3, 4, 4])

In [17]:
%%time
list1 =[x for x in range(1,1001)]
list2 =[x for x in range(2001, 3001)]
list3 =[]
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])

CPU times: total: 0 ns
Wall time: 417 μs


In [19]:
%%time
arr1 = np.array([x for x in range(1,1001)])
arr2 = np.array([x for x in range(2001, 3001)])
arr3 =arr1+arr2

CPU times: total: 0 ns
Wall time: 373 μs


In [21]:
import sys
list1 = [23,45,67,89]
sys.getsizeof(list1[0])*len(list1)

112

In [22]:
arr1 = np.array([23,45,67,89])
arr1.itemsize*arr1.size

32

## multidimentional Array

In [3]:
import numpy as np

In [4]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr1.ndim

2

In [6]:
arr1.shape

(2, 4)

In [9]:
arr1 =np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr1 =np.array([[[1,2],
               [3,4]],

               [[5,6],
                [7,8]]])
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr1.shape

(2, 2, 2)

In [19]:
arr2 = np.array([[[10,20,30],
                  [40,50,60],
                 [70,80,90]],

                 [[1,2,3],
                  [4,5,6],
                  [7,8,9]]])
arr2

array([[[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [20]:
arr2.ndim

3

In [21]:
arr2.shape

(2, 3, 3)

## broadcasting

In [22]:
arr1 = np.array([[10,20,30,40],
                 [50,60,70,80]])
arr2 =np.array([1,2,3,4])

In [24]:
arr3 =arr1 + arr2
arr3

array([[11, 22, 33, 44],
       [51, 62, 73, 84]])

In [62]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 =np.array([1,2,3,4])


In [63]:
arr2 =np.pad(arr2,(0,3))
arr2

array([1, 2, 3, 4, 0, 0, 0])

## Differenct ways to array

In [35]:
list1 = [10,45,67]
arr1 = np.array(list1)

In [36]:
arr1

array([10, 45, 67])

In [37]:
t1= (1,2,3)
arr1 =np.array(t1)
arr1

array([1, 2, 3])

In [38]:
s1 ={1,2,3}
arr1 = np.array(s1)
arr1

array({1, 2, 3}, dtype=object)

In [44]:
arr1.size

1

In [45]:
arr1 = np.arange(1,11)

In [46]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr1 =np.arange(1,50,5)
arr1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [51]:
arr1 =np.random.randint(1,50,5)
arr1

array([16, 18,  1,  7, 31], dtype=int32)

In [56]:
arr1 =np.linspace(1,10,25)
arr1

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [57]:
arr1 =np.random.rand(10)
arr1

array([0.24086323, 0.02081645, 0.61019284, 0.89056827, 0.56015716,
       0.62340288, 0.78724213, 0.30747132, 0.09308392, 0.80607418])

In [58]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [59]:
arr1 = np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
import numpy as np

## different functions

In [2]:
arr1= np.random.randint(1,50,25)
arr1

array([38, 34, 41, 23, 27, 21,  1,  2,  7, 25,  4, 12,  1, 20, 33, 49, 48,
       36,  6, 17,  7, 22, 33, 40, 14], dtype=int32)

In [3]:
arr1 = arr1.reshape(5,5)
arr1

array([[38, 34, 41, 23, 27],
       [21,  1,  2,  7, 25],
       [ 4, 12,  1, 20, 33],
       [49, 48, 36,  6, 17],
       [ 7, 22, 33, 40, 14]], dtype=int32)

In [10]:
arr2 =np.random.randint(1,100,10)
arr2

array([94, 33, 72, 11, 57, 90, 60, 45, 30, 87], dtype=int32)

In [12]:
arr2.min()


np.int32(11)

In [11]:
arr2.max()

np.int32(94)

In [13]:
arr2.mean()

np.float64(57.9)

In [14]:
arr2.sum()

np.int64(579)

## selection

In [15]:
arr2

array([94, 33, 72, 11, 57, 90, 60, 45, 30, 87], dtype=int32)

In [16]:
arr2[5]

np.int32(90)

In [17]:
arr2[0:2]

array([94, 33], dtype=int32)

In [19]:
arr2[3:]

array([11, 57, 90, 60, 45, 30, 87], dtype=int32)

In [20]:
arr2[2:8]

array([72, 11, 57, 90, 60, 45], dtype=int32)

In [21]:
arr1

array([[38, 34, 41, 23, 27],
       [21,  1,  2,  7, 25],
       [ 4, 12,  1, 20, 33],
       [49, 48, 36,  6, 17],
       [ 7, 22, 33, 40, 14]], dtype=int32)

In [22]:
arr1[3]

array([49, 48, 36,  6, 17], dtype=int32)

In [23]:
arr1[2,2]

np.int32(1)

In [24]:
arr1[2:4]

array([[ 4, 12,  1, 20, 33],
       [49, 48, 36,  6, 17]], dtype=int32)

In [25]:
arr2[3:]

array([11, 57, 90, 60, 45, 30, 87], dtype=int32)

In [26]:
arr1[3:]

array([[49, 48, 36,  6, 17],
       [ 7, 22, 33, 40, 14]], dtype=int32)

In [27]:
arr1[3,3]

np.int32(6)

In [28]:
arr1[3,4]

np.int32(17)

In [29]:
arr1[2,1:4]

array([12,  1, 20], dtype=int32)

In [30]:
arr1[3,0:4]

array([49, 48, 36,  6], dtype=int32)

In [31]:
arr1[2:4,2]

array([ 1, 36], dtype=int32)

In [32]:
arr2

array([94, 33, 72, 11, 57, 90, 60, 45, 30, 87], dtype=int32)

## Conditional selection

In [34]:
arr2 [arr2%2 ==0]

array([94, 72, 90, 60, 30], dtype=int32)

In [35]:
arr2[arr2<50]

array([33, 11, 45, 30], dtype=int32)

In [37]:
arr2[(arr2>50) & (arr2 % 2 ==0)]

array([94, 72, 90, 60], dtype=int32)

In [38]:
arr2

array([94, 33, 72, 11, 57, 90, 60, 45, 30, 87], dtype=int32)

In [43]:
arr3 = np.where(arr2%2==0, 2,-1)
arr3

array([ 2, -1,  2, -1, -1,  2,  2, -1,  2, -1])

In [45]:
arr2.sort()
arr2

array([11, 30, 33, 45, 57, 60, 72, 87, 90, 94], dtype=int32)

In [46]:
arr2.sort(axis =0)

In [47]:
arr2

array([11, 30, 33, 45, 57, 60, 72, 87, 90, 94], dtype=int32)

In [49]:
arr4=np.where(arr2%2 !=0, 0, arr2)
arr4

array([ 0, 30,  0,  0,  0, 60, 72,  0, 90, 94], dtype=int32)